package megane6.weplanet.domain.entity.enumfolder;

/** fan_badge.badge_code 값 목록 (name() 이 DB 값이라 이름을 바꾸면 안 됨). */
public enum BadgeCode {
	
	// 일반 배지
	BASIC_FIRST_JOIN,
	BASIC_FIRST_POST,
	BASIC_COMMENT_5,
	BASIC_MEDIA_VIEW,
	BASIC_DAY_100,
	BASIC_DAY_200,
	BASIC_DAY_300,
	BASIC_LIKE_10,
	BASIC_LIKED_5,
	BASIC_FOLLOW_ARTIST,
	BASIC_SHOP_PURCHASE,
	BASIC_LIVE_VIEW,
	BASIC_YEAR_1,
	BASIC_YEAR_2,
	BASIC_YEAR_3,
	
	// 스페셜 배지
	SPECIAL_DEBUT_1,
	SPECIAL_DEBUT_2,
	SPECIAL_DEBUT_3,
	SPECIAL_FOLLOWER_10,
	SPECIAL_MEMBERSHIP_1,
	SPECIAL_MEMBERSHIP_2,
	SPECIAL_MEMBERSHIP_3,
	SPECIAL_MEMBERSHIP_4,
	SPECIAL_MEMBERSHIP_5,
	SPECIAL_PROJECT_CREATE
}