spring.application.name=weplanet

# 소스 코드(HTML, JS, CSS 등 정적 리소스)가 바꼈을 때, 브라우저를 자동으로 새로고침 해주는 기능
spring.devtools.livereload.enabled=true

# url
server.port=9999
server.servlet.context-path=/

# log
logging.level.root=info
logging.level.6megane.weplanet=debug

## MySQL ####################################################
# 인텔리제이 플러그인(EnvFile) 도움 없이, 스프링 부트가 스스로 .env 파일을 직접 읽어서 연동하게 만드는 설정
spring.config.import=optional:file:.env[.properties]

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

### Hibernate SQL ??
# SQL ? ??
logging.level.org.hibernate.SQL=debug
# ???? ? ??
logging.level.org.hibernate.type.descriptor.sql=trace
logging.level.org.hibernate.orm.jdbc.bind=TRACE
### JPA ??
# ??? ?? ??/??
spring.jpa.hibernate.ddl-auto=validate
# Hibernate가 JDBC 연결 정보로 자동 인식하므로 dialect는 명시하지 않음 (최신 Hibernate에서 MySQL8Dialect 클래스 삭제됨)

### SQL ?? ?? ??
# System.out ?? ???? (logger ??? ??)
spring.jpa.show-sql=false
# Logger ?? SQL ??
spring.jpa.properties.hibernate.show_sql=true
# SQL ??? ??
spring.jpa.properties.hibernate.format_sql=true